services:
    nginx:
        container_name: nginx-server
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
