services:
    nginx:
        container_name: nginx-server
        environment:
            - VIRTUAL_HOST=nginx.pajordan.com
            - LETSENCRYPT_HOST=nginx.pajordan.com
        networks:
            - net
        image: nginx:latest
        volumes:
            - ./src:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: "always"
networks:
    net:
        external: true
        name: net
